"""add owner_id to jobs and user_id to candidates

Revision ID: 3bb001b237e6
Revises: 781241c272aa
Create Date: 2026-07-13 16:14:11.747080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb001b237e6'
down_revision: Union[str, Sequence[str], None] = '781241c272aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('candidates_user_id_fkey', 'candidates', 'users', ['user_id'], ['id'])
    op.add_column('jobs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('jobs_owner_id_fkey', 'jobs', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_owner_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'owner_id')
    op.drop_constraint('candidates_user_id_fkey', 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'user_id')
    # ### end Alembic commands ###
